all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: vcs_kafka
zookeeper:
  hosts:
   zookeeper1: 

kafka_broker:
  hosts:
   kafkabroker1:

kafka_connect:
  hosts:  
    kafkabroker1:

ksql:
  hosts:  
    kafkabroker1:

confluent_cli:
  hosts:
    zookeeper1: