all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: vcs_kafka
zookeeper:
  hosts:
   192.168.99.104: 

kafka_broker:
  hosts:
   192.168.99.105:

kafka_connect:
  hosts:  
    192.168.99.105:
