- name: checking if the confluent cli bundle is present in /tmp directory
  stat: 
     path: "/tmp/{{ confluent_cli_package_name }}"
  delegate_to: 127.0.0.1
  register: cli_bundle_download_status

- name: Download the tar ball from the confluent website
  get_url:
   url: "{{ confluent_cli_url }}"
   dest: "/tmp"
  delegate_to: 127.0.0.1
  when: cli_bundle_download_status.stat.exists == false

- name: checking if the confluent cli bundle is present in confluent bundle directory
  stat: 
     path: "{{ confluent_appdir }}/bundles/{{ confluent_cli_package_name }}"
  register: confluent_cli_bundle_status

- name: copy the confluent cli bundle to the location on remote machine
  copy:
    src: "/tmp/{{ confluent_cli_package_name }}"
    dest: "{{ confluent_appdir }}/bundles/{{ confluent_cli_package_name }}"
  when: confluent_cli_bundle_status.stat.exists == false

- name: checking if the cli bundle is extracted in confluent bundle directory
  stat: 
     path: "{{ confluent_appdir }}/bundles/confluent"
  register: confluent_cli_bundle_extract_status

- name: Extracting the tar ball to bundles location 
  unarchive:
    src: "{{ confluent_appdir }}/bundles/{{ confluent_cli_package_name }}"
    dest: "{{ confluent_appdir }}/bundles/"
    remote_src: yes
  when: confluent_cli_bundle_extract_status.stat.exists == false