- name: zookeeper create directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0750
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
  with_items:
    - "{{ zk_etc_dir }}"
    - "{{ zk_data_dir }}"
    - "{{ zk_log_dir }}"

- name: zookeeper myid file
  template:
    src: myid.j2
    dest: "{{ zk_data_dir }}/myid"
    mode: 0555
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"

- name: zookeeper create configs
  template:
    src: zookeeper.properties.j2
    dest: "{{ zk_etc_dir }}/zookeeper.properties"
    mode: 0400
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
  register: zookeeper_config

#- name: copy truststore and keystore to the config directory
#  copy:
#    src: "{{ playbook_dir }}/tls/certs/{{ item }}"
#    dest: "{{ zk_etc_dir }}"
#  with_items:
#    - "zookeeper.keystore.jks"
#    - "truststore.jks"

- name: checking if the bundle is present in /tmp directory
  stat: 
     path: "/tmp/{{ java_agent_jar  }}"
  delegate_to: 127.0.0.1
  register: prometheus_java_agent_download

- name: Download the prometheus_java_agent_url
  get_url:
   url: "{{ prometheus_java_agent_url }}"
   dest: "/tmp"
  delegate_to: 127.0.0.1
  become: yes
  when: prometheus_java_agent_download.stat.exists == false

- name: checking if the prometheus_java_agent_url is in etc directory
  stat: 
     path: "{{ zk_etc_dir }}/{{ java_agent_jar }}"
  register: prometheus_java_agent_copy

- name: copy the confluent etc to the location on remote machine
  copy:
    src: "/tmp/{{ java_agent_jar }}"
    dest: "{{ zk_etc_dir }}"
  when: prometheus_java_agent_copy.stat.exists == false

- name: Deploy JMX Exporter Config File
  copy:
    src: "zookeeper.yml"
    dest: "{{ zk_etc_dir }}"
    mode: 0640
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"