- name: Kafka Broker create directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0750
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  with_items:
    - "{{ kafka_etc_dir }}"
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"

- name: Create kafka broker configs
  template:
    src: server.properties.j2
    dest: "{{ kafka_etc_dir }}/server.properties"
    mode: 0400
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

- name: Copy Log4j Properties
  template:
    src: log4j.properties.j2
    dest: "{{ kafka_etc_dir }}/log4j.properties"
    mode: 0400
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

#- name: copy truststore and keystore to the config directory
#  copy:
#    src: "{{ playbook_dir }}/tls/certs/{{ item }}"
#    dest: "{{ kafka_etc_dir }}"
#  with_items:
#    - "broker-server.keystore.jks"
#    - "truststore.jks"
#    - "zookeeper.keystore.jks"

- name: Download the prometheus_java_agent_url
  get_url:
   url: "{{ prometheus_java_agent_url }}"
   dest: "/tmp"
  delegate_to: 127.0.0.1
  become: yes
  when: prometheus_java_agent_download.stat.exists == false

- name: checking if the prometheus_java_agent_url is in etc directory
  stat: 
     path: "{{ kafka_etc_dir }}/{{ java_agent_jar }}"
  register: prometheus_java_agent_download

- name: copy the confluent etc to the location on remote machine
  copy:
    src: "/tmp/{{ java_agent_jar }}"
    dest: "{{ kafka_etc_dir }}"
  when: confluent_bundle_status.stat.exists == false

- name: copy the confluent etc to the location on remote machine
  copy:
    src: "/tmp/{{ java_agent_jar }}"
    dest: "{{ kafka_etc_dir }}"
  when: confluent_bundle_status.stat.exists == false

- name: Deploy JMX Exporter Config File
  copy:
    src: "kafka.yml"
    dest: "{{ kafka_etc_dir }}"
    mode: 0640
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"